/*****************************************************************************
 *																			 *
 *								Protocol File								 *
 *																			 *
 *		File	: DB_Define.cs
 *																			 *
 *		Desc	: Generated by Morpheus										 *
 *																			 *
 *****************************************************************************/
//-----------------------------------------------------------------------------
//	Include Files & Define
//-----------------------------------------------------------------------------
using System.Collections.Generic;


namespace table.db {

//-----------------------------------------------------------------------------
//	Enumerations
//-----------------------------------------------------------------------------
[System.Flags]
public enum Novel
{
	Universal = 1,
	Ragnarok = 2,
	Empyrea = 4,
	All = 7,
}

[System.Flags]
public enum E_EntityResType
{
	Static,
	Tile,
	Anim,
	Effect,
	Actor,
	UI,
	Max,
}

[System.Flags]
public enum PC_Class
{
	knight,
	warrior,
	thief,
	archer,
	wizard,
	healer,
}

[System.Flags]
public enum E_StatFormula
{
	None,
	Physical_Attack,
	Have_Weight,
	Physical_DBuf,
	Far_Attack,
	Attack_Grade,
	Defend_Grade,
	Physical_Critical,
	Far_Critical,
	Avoid,
	HP,
	HP_Recover,
	Physical_DBuf_Resist,
	Magic_Attack,
	Magic_Critical,
	MP,
	Magic_DBuf,
	MP_Recover,
	Magic_DBuf_Resist,
	LevelUp_Stat_Ratio = 101,
}

[System.Flags]
public enum E_StatusEffectType
{
	None,
	Armor,
	ArmorPercent,
	MaxHealth,
	MaxHealthPercent,
	MaxEnergy,
	MaxEnergyPercent,
	Strength,
	StrengthPercent,
	Endurance,
	EndurancePercent,
	Dexterity,
	DexterityPercent,
	Intelligence,
	IntelligencePercent,
	Dodge,
	DodgePercent,
	ResistAll,
	ResistAllPercent,
	PhysicalDamage,
	PhysicalDamagePercent,
	PhysicalCritChance,
	PhysicalCritChancePercent,
	ElementalDamage,
	ElementalDamagePercent,
	ElementalCritChance,
	ElementalCritChancePercent,
	MovementSpeed,
	MovementSpeedPercent,
	AttackSpeed,
	AttackSpeedPercent,
	AirDamage,
	EarthDamage,
	FireDamage,
	WaterDamage,
	FireResistance,
	WaterResistance,
	AirResistance,
	EarthResistance,
	CritChanceAll,
	CritChanceAllPercent,
	AttackPower,
	AttackPowerPercent,
	TreasureFinding,
	TreasureFindingPercent,
	XPBonus,
	GoldFinding,
	GoldFindingPercent,
	ArmorByStrPercent,
	HealthByIntPercent,
	DamageVsStunnedPercent,
	AbilityCooldownPercent,
	ElementalResistancePercent,
	Damage,
	Invulnerable,
	VanguardRatingBonus,
	WeaponDamage,
	DamageAbsorption,
	MinDamage,
	MaxDamage,
	CritDamage,
	PhysicalCritRating,
	ElementalCritRating,
	MovementSpeedBonus,
	AttackSpeedBonus,
	HPRecovery,
	MPRecovery,
	Invalid,
}

[System.Flags]
public enum E_ElementType
{
	None,
	Normal,
	Air,
	Earth,
	Electricity,
	Fire,
	Ice,
	Poison,
	Water,
}

[System.Flags]
public enum E_ScopeType
{
	PC,
	PCAll,
	OnePC_Dead,
	Enemy,
	EnemyAll,
	RandomEnemy,
}

[System.Flags]
public enum E_OccasionType
{
	Always,
	Battle,
	Menu,
	Never,
}

[System.Flags]
public enum E_HitType
{
	CertainHit,
	PhysicalAttack,
	MagicalAttack,
}

[System.Flags]
public enum E_DamageType
{
	HPDamage,
	MPDamage,
	HPRecover,
	MPRecover,
	HPDrain,
	MPDrain,
}

[System.Flags]
public enum E_RestrictionType
{
	None,
	AttackEnemy,
	AttackAnyone,
	AttackAlly,
	CannotMove,
}

[System.Flags]
public enum E_AutoRemoveType
{
	None,
	ActionEnd,
	TurnEnd,
}

}; // namespace table.db
/* EOF */
